export { default as Home } from './Home/Home'
export { default as AboutMe } from './AboutMe/AboutMe'
export { default as Resume } from './Resume/Resume'
export { default as Skills } from './Skills/Skills'
export { default as Projects } from './Projects/Projects'
export { default as Contact } from './Contact/Contact'
